#!/usr/bin/env ruby

# Copied from https://stackoverflow.com/a/15104926/8650655
def count_lines(ext)
  o = 0 # Number of files
  n = 0 # Number of lines of code
  m = 0 # Number of lines of comments

  files = Dir.glob("./src/**/*." + ext)

  files.each do |f|
    next if f.index("vendor")
    next if File.directory?(f)
    o += 1
    i = 0
    File.read(f).each_line do |line|
      if line.strip.start_with? "#"
        m += 1
        next
      end
      i += 1
    end
    n += i
  end

  puts "#{o} files."
  puts "#{n} lines of code."
  puts "#{(n.to_f/o.to_f).round(2)} LOC/file."
  puts "#{m} lines of comments."
end

count_lines("cr")
